requirements:
#  mmhash3: "mmh3"
  email-validator: "email-validator"
  docstring-parser: docstring_parser
  ruamel-yaml: ruamel.yaml
channels:
  - dharpa
  - conda-forge

entry_points:
  kiara: kiara.interfaces.cli:cli

host_requirements:
  - python
  - pip
  - hatchling
  - hatch-vcs

test:
  imports:
    - kiara
    - kiara.interfaces.python_api
  source_files:
    - tests
  commands:
    - kiara module list
#    - kiara data list#
    - kiara operation list
#    - pytest tests#
#  requires:#
#    - pytest#
