requirements:
  mmhash3: "mmh3"
  email-validator: "email-validator>=1.0.0"
  docstring-parser: docstring_parser

channels:
  - dharpa
  - conda-forge

entry_points:
  kiara: kiara.interfaces.cli:cli

host_requirements:
  - pip
  - python
  - setuptools
  - setuptools_scm
  - setuptools_scm_git_archive

test:
  imports:
    - kiara
    - kiara.interfaces.python_api
  source_files:
    - tests
  commands:
    - kiara module list
#    - kiara data list#
    - kiara operation list
#    - pytest tests#
#  requires:#
#    - pytest#
